# Generated by Django 4.0.4 on 2022-05-29 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFamiliares', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiares',
            name='nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
