# Generated by Django 4.0.4 on 2022-05-29 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFamiliares', '0002_familiares_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiares',
            name='relacion',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
