# Generated by Django 4.0.4 on 2022-05-29 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFamiliares', '0004_alter_familiares_relacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiares',
            name='relacion',
            field=models.CharField(blank=True, default='Ingresar Relacion', max_length=30, null=True),
        ),
    ]
