# Generated by Django 4.0.4 on 2022-05-29 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFamiliares', '0005_alter_familiares_relacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiares',
            name='relacion',
            field=models.CharField(default='Ingresar Relacion', max_length=30),
        ),
    ]
